version: '3.7'

services:
  naming-server:
    image: in28min/mmv2-netflix-eureka-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
        - "8761:8761"
    networks:
        - currency-network
        
  rabbitmq:
    image: rabbitmq:3.6.15-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rmquser
      RABBITMQ_DEFAULT_PASS: rmquser
    ports:
      - "5673:5672"
    networks:
      - currency-network
      
  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    environment:
      - RABBIT_URI=amqp://rmquser:rmquser@rabbitmq
    depends_on:
      - rabbitmq
    restart: always #Restart if there is a problem starting up
        
  api-gateway:
    image: in28min/mmv2-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
        - "8765:8765"
    environment:
        eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
        spring.zipkin.baseurl: http://zipkin-server:9411
        spring.zipkin_sender_type: rabbit
        spring.rabbitmq.host: rabbitmq
        spring.rabbitmq.port: 5672
        spring.rabbitmq.username: rmquser
        spring.rabbitmq.password: rmquser
    networks:
        - currency-network
    depends_on:
        - naming-server
        
  currency-exchange:
    image: in28min/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
        - "8000:8000"
    environment:
        eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
        spring.zipkin.baseurl: http://zipkin-server:9411
        spring.zipkin_sender_type: rabbit
        spring.rabbitmq.host: rabbitmq
        spring.rabbitmq.port: 5672
        spring.rabbitmq.username: rmquser
        spring.rabbitmq.password: rmquser
    
    networks:
        - currency-network
    depends_on:
        - naming-server
        
  currency-conversion:
    image: in28min/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
        - "8100:8100"
    networks:
        - currency-network
    environment:
        eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
        spring.zipkin.baseurl: http://zipkin-server:9411
        spring.zipkin_sender_type: rabbit
        spring.rabbitmq.host: rabbitmq
        spring.rabbitmq.port: 5672
        spring.rabbitmq.username: rmquser
        spring.rabbitmq.password: rmquser
    depends_on:
        - naming-server
        - api-gateway
        
networks:
    currency-network:
        